golf_coordinator/Courses/urls.py
from Courses import views
from django.urls import path, include, re_path

app_name = 'courses'

urlpatterns = [
    # url for new course form. currently not being used.
    path(r'new/', views.CreateCourseView, name='course_new'),
    # lists all of the courses
    path(r'golf_course_list/', views.Golf_CourseListView.as_view(), name='golf_course_list'),
    # this is used when a tee is selected from the golf_course_list view
    re_path(r'golf_tee_list/(?P<pk>\d+)', views.Golf_TeeDetailView.as_view(), name='golf_tee_detail'),
    # not being used currently.
    re_path(r'golf_tee_list/new_tee/', views.Golf_TeeCreateView.as_view(), name='tee_new'),
]

golf_coordinator/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    # users login form
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # users logout form
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    # users can sign up and register for the site. 
    path('signup/', views.register, name='signup'),
]

golf_coordinator/golf_coordinator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', views.AboutPage.as_view(), name='about'),
    path('', include('golf_trip.urls', namespace='golf_trip')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('round/', include('GolfRound.urls', namespace='round')),
    path('courses/', include('Courses.urls', namespace='courses')),
    path('teams/', include('teams.urls', namespace='teams')),
    path('bookie/', include('bookie.urls', namespace='bookie')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golf_coordinator/golf_trip/urls.py
from golf_trip import views
from django.urls import path, include, re_path

app_name = 'golf_trip'

urlpatterns = [
    
    path(r'', views.HomePage.as_view(), name='home'),
    # look back on previous trips
    path('history/', views.EventHistoryView.as_view(), name='event_history'),
    # if the user selects to see streamsong data
    path('history/streamsong', views.HistoryStreamsong.as_view(), name='streamsong'),
    # if it's a current trip, all events are shown by the day
    path('events/', views.EventListView.as_view(), name='events_list'),
    # if the event day is selected, that day's courses and tee times are displayed.
    re_path(r'^events/(?P<event_day>\d{4}-\d{2}-\d{2})/$', views.EventTeeTimeListView.as_view(), name='event_teetime'),
    # currently not being used, but intended to show details of the event
    path(r'^teetime/<int:pk>', views.EventTeeTimeDetailView.as_view(), name='teetime_detail'),
    path('events/<int:pk>', views.EventDetailView.as_view(), name='eventDetail'),
    # Lists all players on the trip
    path('players/', views.PlayersListView.as_view(), name='players_list'),
    path('players/<int:pk>', views.PlayersDetailView.as_view(), name='player_detail'),
    path('teams/', views.TeamListView.as_view(), name='team_list'),
    path('standings/', views.TripStandingsTemplateView.as_view(), name='trip_standings'),
]

golf_coordinator/teams/urls.py
from django.urls import path, re_path
from . import views

app_name = 'teams'



urlpatterns = [
    path('', views.ListTeam.as_view(), name='all'),
    path('new/', views.CreateTeam.as_view(), name='create'),
    # re_path('rounds/in/(?P<team>[-\w]+)/', views.SingleGroup.as_view(), name='single'),
]

golf_coordinator/templates/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <!-- Header-->
            <header class="py-5">
                <div class="container px-5">
                    <div class="row justify-content-center">
                        <div class="col-lg-8 col-xxl-6">
                            <div class="text-center my-5">
                                <h1 class="fw-bolder mb-3">Tracking golf trips made simple.</h1>
                                <p class="lead fw-normal text-muted mb-4">Running a golf trip can be difficult. This application looks to help trip oganizers with the logistics of a golf trip, like the players, teams, schedule, and gambling. <br> <strong>(in Beta)</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- About section one-->
            <section class="py-5 bg-light" id="scroll-target">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'arnold-palmer-90th-goofy-disney-golf.jpg' %}" /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Inaugural Trip (2021)</h2>
                            <p class="lead fw-normal text-muted mb-0">To start off the golf trip, the group started in the golf capital of the world, Orlando, FL with 12 guys.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section two-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'Streamsong_walk.webp' %}" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Streamsong (2022)</h2>
                            <p class="lead fw-normal text-muted mb-0">A successful inaugural trip inspired the group to increase the size to 16 players, and decided to splurge. This brought the group to Streamsong, a beautiful resort outside of Tampa, FL</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section three-->
            <section class="py-5 bg-light" id="scroll-target">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'TreetopsSignature0121.jpg' %}" /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Michigan (2023)</h2>
                            <p class="lead fw-normal text-muted mb-0">The third annual trip is increasing to 20 players and taking the trip up to Michigan to play Arcadia Bluffs and Treetops.</p>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Golf Trip Course Manager</div></div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
{% endblock %}

golf_coordinator/templates/base.html
{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% bootstrap_messages %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Golf Trip Manager</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Jquery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
      
       
        
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
           {% include "navbar.html" %}
    {% block content %}
    
    {% endblock %}
</html>

golf_coordinator/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">Business Name or Tagline</h1>
                    <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                    <a class="btn btn-primary" href="#!">Call to Action!</a>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card One</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Two</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Three</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

golf_coordinator/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'golf_trip:home' %}">
            <i class="fa-solid fa-golf-ball-tee"></i>  Golf Trip Manager
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if user.is_authenticated and user.is_active %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
            <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
            <a class="nav-link" href={% url 'courses:golf_course_list' %}>Course List</a>
            </ul>
        </div>
    </div>
</nav>