golf_coordinator/golf_coordinator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', views.AboutPage.as_view(), name='about'),
    path('', include('golf_trip.urls', namespace='golf_trip')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('round/', include('GolfRound.urls', namespace='round')),
    path('courses/', include('Courses.urls', namespace='courses')),
    path('teams/', include('teams.urls', namespace='teams')),
    path('bookie/', include('bookie.urls', namespace='bookie')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golf_coordinator/teams/urls.py
from django.urls import path, re_path
from . import views

app_name = 'teams'



urlpatterns = [
    path('', views.ListTeam.as_view(), name='all'),
    path('new/', views.CreateTeam.as_view(), name='create'),
    # re_path('rounds/in/(?P<team>[-\w]+)/', views.SingleGroup.as_view(), name='single'),
]

golf_coordinator/teams/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse
from accounts.models import Golfer
# Create your models here.

User = get_user_model()
register = template.Library()

class Team(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(Golfer, through='TeamMember')
    team_score = models.DecimalField(max_digits=3, decimal_places=1, default=0)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('teams:single', kwargs={'name':self.name})
    
    class Meta:
        ordering = ['name']


class TeamMember(models.Model):
    team = models.ForeignKey(Team, related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(Golfer, related_name='user_teams', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('team', 'user')

golf_coordinator/teams/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from teams.models import Team, TeamMember

# Create your views here.


class CreateTeam(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Team

class ListTeam(generic.ListView):
    model = Team

golf_coordinator/teams/templates/teams/team_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        {% block preteam %}{% endblock %}
        {% block team_content %}{% endblock %}
        {% block roundteam %}{% endblock %}
    </div>
</div>

{% endblock %}

golf_coordinator/teams/templates/teams/team_form.html
{% extends 'teams/team_base.html' %}
{% load bootstrap5 %}

{% block team_content %}
<h4>Create a New Team!!</h4>

    <form action="{% url 'teams:create' %}" method="POST" id='teamForm'>
        {% csrf_token %}
        {% bootstrap_form form%}
        <input type="submit" class='btn btn-primary btn-large' value="Create">
    </form>

{% endblock  %}