golf_coordinator/Courses/urls.py
from Courses import views
from django.urls import path, include, re_path

app_name = 'courses'

urlpatterns = [
    # url for new course form. currently not being used.
    path(r'new/', views.CreateCourseView, name='course_new'),
    # lists all of the courses
    path(r'golf_course_list/', views.Golf_CourseListView.as_view(), name='golf_course_list'),
    # this is used when a tee is selected from the golf_course_list view
    re_path(r'golf_tee_list/(?P<pk>\d+)', views.Golf_TeeDetailView.as_view(), name='golf_tee_detail'),
    # not being used currently.
    re_path(r'golf_tee_list/new_tee/', views.Golf_TeeCreateView.as_view(), name='tee_new'),
]

golf_coordinator/GolfRound/urls.py
from GolfRound import views
from django.urls import path, re_path

app_name = 'round'

urlpatterns = [
    path(r'submit/<int:teetime_pk>', views.RoundSubmissionView, name='round_submit'),
    path(r'teetime/<int:pk>', views.CompletedRoundView.as_view(), name="completed_round"),
    # path(r'round/<int:pk>', views.RoundDetailView.as_view(), name='round_detail'),
    # path('ajax/load-tees/', views.load_tees, name='ajax_load_tees'),  # <-- this one here
]

golf_coordinator/bookie/urls.py
from bookie import views
from django.urls import path, include, re_path
from bookie.views import BetTeeTimeView, GolfBetListView

app_name = 'bookie'

urlpatterns = [
    # path('player_bet/', BetPVPCreateView.as_view(), name='bet_pvp'),
    path('bet_teetime/<int:teetime_pk>', BetTeeTimeView, name='bet_teetime'),
    path('bet_overview/', GolfBetListView.as_view(), name='bet_overview'),
    # url for new course form. currently not being used.
    # path(r'new/', views.CreateCourseView, name='course_new'),
   
]

golf_coordinator/golf_coordinator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', views.AboutPage.as_view(), name='about'),
    path('', include('golf_trip.urls', namespace='golf_trip')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('round/', include('GolfRound.urls', namespace='round')),
    path('courses/', include('Courses.urls', namespace='courses')),
    path('teams/', include('teams.urls', namespace='teams')),
    path('bookie/', include('bookie.urls', namespace='bookie')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golf_coordinator/golf_trip/urls.py
from golf_trip import views
from django.urls import path, include, re_path

app_name = 'golf_trip'

urlpatterns = [
    
    path(r'', views.HomePage.as_view(), name='home'),
    # look back on previous trips
    path('history/', views.EventHistoryView.as_view(), name='event_history'),
    # if the user selects to see streamsong data
    path('history/streamsong', views.HistoryStreamsong.as_view(), name='streamsong'),
    # if it's a current trip, all events are shown by the day
    path('events/', views.EventListView.as_view(), name='events_list'),
    # if the event day is selected, that day's courses and tee times are displayed.
    re_path(r'^events/(?P<event_day>\d{4}-\d{2}-\d{2})/$', views.EventTeeTimeListView.as_view(), name='event_teetime'),
    # currently not being used, but intended to show details of the event
    path(r'^teetime/<int:pk>', views.EventTeeTimeDetailView.as_view(), name='teetime_detail'),
    path('events/<int:pk>', views.EventDetailView.as_view(), name='eventDetail'),
    # Lists all players on the trip
    path('players/', views.PlayersListView.as_view(), name='players_list'),
    path('players/<int:pk>', views.PlayersDetailView.as_view(), name='player_detail'),
    path('teams/', views.TeamListView.as_view(), name='team_list'),
    path('standings/', views.TripStandingsTemplateView.as_view(), name='trip_standings'),
]

golf_coordinator/teams/urls.py
from django.urls import path, re_path
from . import views

app_name = 'teams'



urlpatterns = [
    path('', views.ListTeam.as_view(), name='all'),
    path('new/', views.CreateTeam.as_view(), name='create'),
    # re_path('rounds/in/(?P<team>[-\w]+)/', views.SingleGroup.as_view(), name='single'),
]

golf_coordinator/GolfRound/models.py
from django.db import models
from golf_trip.models import Trip_TeeTime, Trip_Golfer


    

class Round_Score(models.Model):
    tee_time = models.ForeignKey(Trip_TeeTime, on_delete=models.PROTECT)
    round_golfer = models.CharField(max_length=255)
    golfer_pk = models.ForeignKey(Trip_Golfer, on_delete=models.PROTECT)
    golfer_index = models.DecimalField(decimal_places=1, max_digits=3)
    hole_1_score = models.IntegerField()
    hole_2_score = models.IntegerField()
    hole_3_score = models.IntegerField()
    hole_4_score = models.IntegerField()
    hole_5_score = models.IntegerField()
    hole_6_score = models.IntegerField()
    hole_7_score = models.IntegerField()
    hole_8_score = models.IntegerField()
    hole_9_score = models.IntegerField()
    hole_10_score = models.IntegerField()
    hole_11_score = models.IntegerField()
    hole_12_score = models.IntegerField()
    hole_13_score = models.IntegerField()
    hole_14_score = models.IntegerField()
    hole_15_score = models.IntegerField()
    hole_16_score = models.IntegerField()
    hole_17_score = models.IntegerField()
    hole_18_score = models.IntegerField()
    total_score = models.IntegerField(default=0)
    net_score = models.IntegerField(default=0)

    def __str__(self):
        return "{}_{}".format(self.round_golfer, self.tee_time)
    

class Net_Round_Score(models.Model):
    tee_time = models.ForeignKey(Trip_TeeTime, on_delete=models.PROTECT)
    round_golfer = models.CharField(max_length=255)
    golfer_pk = models.ForeignKey(Trip_Golfer, on_delete=models.PROTECT)
    hole_1_score = models.IntegerField()
    hole_2_score = models.IntegerField()
    hole_3_score = models.IntegerField()
    hole_4_score = models.IntegerField()
    hole_5_score = models.IntegerField()
    hole_6_score = models.IntegerField()
    hole_7_score = models.IntegerField()
    hole_8_score = models.IntegerField()
    hole_9_score = models.IntegerField()
    hole_10_score = models.IntegerField()
    hole_11_score = models.IntegerField()
    hole_12_score = models.IntegerField()
    hole_13_score = models.IntegerField()
    hole_14_score = models.IntegerField()
    hole_15_score = models.IntegerField()
    hole_16_score = models.IntegerField()
    hole_17_score = models.IntegerField()
    hole_18_score = models.IntegerField()
    total_score = models.IntegerField()
    net_score = models.IntegerField()

    def __str__(self):
        return "{}_{}".format(self.round_golfer, self.tee_time)
    

class Par3_Round_Score(models.Model):
    tee_time = models.ForeignKey(Trip_TeeTime, on_delete=models.PROTECT)
    round_golfer = models.CharField(max_length=255)
    golfer_pk = models.ForeignKey(Trip_Golfer, on_delete=models.PROTECT)
    golfer_index = models.DecimalField(decimal_places=1, max_digits=3)
    hole_1_score = models.IntegerField()
    hole_2_score = models.IntegerField()
    hole_3_score = models.IntegerField()
    hole_4_score = models.IntegerField()
    hole_5_score = models.IntegerField()
    hole_6_score = models.IntegerField()
    hole_7_score = models.IntegerField()
    hole_8_score = models.IntegerField()
    hole_9_score = models.IntegerField()
    total_score = models.IntegerField(default=0)
    net_score = models.IntegerField(default=0)

    def __str__(self):
        return "{}_{}".format(self.round_golfer, self.tee_time)
    

class Par3_Net_Round_Score(models.Model):
    tee_time = models.ForeignKey(Trip_TeeTime, on_delete=models.PROTECT)
    round_golfer = models.CharField(max_length=255)
    golfer_pk = models.ForeignKey(Trip_Golfer, on_delete=models.PROTECT)
    hole_1_score = models.IntegerField()
    hole_2_score = models.IntegerField()
    hole_3_score = models.IntegerField()
    hole_4_score = models.IntegerField()
    hole_5_score = models.IntegerField()
    hole_6_score = models.IntegerField()
    hole_7_score = models.IntegerField()
    hole_8_score = models.IntegerField()
    hole_9_score = models.IntegerField()
    total_score = models.IntegerField()
    net_score = models.IntegerField()

    def __str__(self):
        return "{}_{}".format(self.round_golfer, self.tee_time)

golf_coordinator/golf_trip/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, DetailView, ListView
from golf_trip.models import *
from bookie.models import *
from bookie.forms import BetTeeTimeForm


class EventHistoryView(ListView):
    model = Golf_Trip

# adds extra context to include the streamsong data for golfers and events. 
class HistoryStreamsong(TemplateView):
    template_name = 'golf_trip/trip_streamsong_index.html'
    extra_context={'golfers': Trip_Golfer.objects.all().filter(trip__trip_name='Streamsong'), 
                   'trip_events':Trip_Event.objects.all().filter(trip__trip_name='Streamsong')}


# sicne michigan is the current trip, the golfer and trip events are fitlered to just contain them.
class HomePage(TemplateView):
    template_name = 'golf_trip/trip_michigan_index.html'
    extra_context={'golfers': Trip_Golfer.objects.all().filter(trip__trip_name='Michigan'), 
                   'trip_events':Trip_Event.objects.all().filter(trip__trip_name='Michigan')}


#list details of the event
class EventDetailView(DetailView):
    model = Trip_Event
    template_name='golf_trip/golf_trip_detail.html'


# lsits all golfers on the michigan trip and orders them by first name
class PlayersListView(ListView):
    model = Trip_Golfer

    def get_queryset(self):
        queryset = Trip_Golfer.objects.all().filter(trip__trip_name='Michigan').order_by('golfer__first_name')
        
        return queryset
    

class PlayersDetailView(DetailView):
    model = Trip_Golfer
    template_name='golf_trip/trip_golfer_detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(PlayersDetailView, self).get_context_data(**kwargs)

    #     bet_info = 
            
    

# 
class EventListView(ListView):
    model = Trip_Event

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(EventListView, self).get_context_data(**kwargs)
        # grabbing the dates for all of the events for the trip
        trip_dates = Trip_Event.objects.all().filter(trip__trip_name='Michigan').values('event_time').distinct()
        # grabbing all the courses for the trip
        trip_courses = Trip_Event.objects.all().filter(trip__trip_name='Michigan')

        context['trip_events'] = trip_courses
        context['trip_dates'] = trip_dates
        return context


class EventTeeTimeListView(ListView):
    model = Trip_TeeTime

    
    def get_queryset(self):
        queryset = Trip_TeeTime.objects.all().filter(tee_time_date=self.kwargs['event_day'])
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(EventTeeTimeListView, self).get_context_data(**kwargs)
        # context['form'] = BetTeeTimeForm()
        return context


class EventTeeTimeDetailView(DetailView):
    model = Trip_TeeTime


class TeamListView(ListView):
    model = Trip_Team
    template_name = 'golf_trip/teams_list.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TeamListView, self).get_context_data(**kwargs)
        # grabbing the dates for all of the events for the trip
        trip_teams = Trip_Team.objects.all().filter(trip__trip_name='Michigan')
        drafted = Trip_Team.objects.all().filter(trip__trip_name='Michigan').exclude(team="Not Drafted")
        not_drafted = Trip_Team.objects.all().filter(trip__trip_name='Michigan').filter(team="Not Drafted")


        context['trip_teams'] = trip_teams
        context['not_drafted'] = not_drafted
        context['drafted'] = drafted
        return context
    
class TripStandingsTemplateView(TemplateView):
    template_name = 'golf_trip/trip_standings.html'
    
    def get_context_data(self, *args, **kwargs):
         # Call the base implementation first to get a context
        context = super(TripStandingsTemplateView, self).get_context_data(**kwargs)

        team_1_members = 'N/A'
        team_2_members = 'N/A'
        try:  
            teams = Trip_Team.objects.all().filter(trip__trip_name='Michigan')
            team_1_members = teams[0].members.all().order_by('-score')
            team_2_members = teams[1].members.all().order_by('-score')
        except:
            team_1_members = teams[2].members.all()
            team_2_members = teams[2].members.all()
        

        completed_rounds = Trip_TeeTime.objects.all().filter(teeTime_Complete=True)
        
        try:
            team_1 = teams[0]
            team_2 = teams[1]
        except:
            team_1 = 'N/A'
            team_2 = 'N/A'

        extra_context={'team_1': team_1, 'team_2': team_2,
                    'team_1_members': team_1_members,
                    'team_2_members': team_2_members,              
                    'trip_events':Trip_Event.objects.all().filter(trip__trip_name='Michigan'),
                    'completed_rounds': completed_rounds}

        context.update(extra_context)

        return context
        

golf_coordinator/golf_trip/templates/golf_trip/golf_trip_list.html
{% extends "base.html" %}
{% block content %}
{% for trip in golf_trip_list %}
<a href="{% url 'golf_trip:streamsong' %}">{{trip.trip_date}} - {{trip.trip_name}}</a>


{% endfor %}

{% endblock %}

golf_coordinator/golf_trip/templates/golf_trip/teams_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h1>Team List</h1>
<div class="container">
    <div class="row align-items-start">
      {% for teams in drafted  %}
      <div class="col">
        <h4>{{teams.team}}</h4>
        {% for golfer in teams.members.all %}
            <li>{{golfer.first_name}} {{golfer.last_name}}</li>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

golf_coordinator/golf_trip/templates/golf_trip/trip_2023_index.html
{% extends "base.html" %}
{% block content %}

{% load static %}




<html>
  <head>
    <title>Golf Trip Manager</title>
    <link rel="stylesheet" href="{% static 'css/overall_css.css' %}">
  </head>

{% block bodyblock %}

<div class="text-center" id="page_header">
  <h1>Golf Trip 2023!</h1>
  <img  id="index_img" src="{% static 'Tree_Tops_Portrait.jpg' %}" alt="My image">
</div>
<div class="text-center">
  <div class="row align-items-top">
    <div class="col">
      <h3>Players</h3>
      {% for golfer in golfers%}
      <div class="container">
          <div class="row">
            <div class="col">
              <ul class="list-group">{{golfer.golfer.first_name}}</ul>
            </div>
            <div class="col">
              <ul class="list-group">{{golfer.golfer.last_name}}<ul>
            </div>
            <div class="col">
              <ul class="list-group">{{golfer.hcp_index}}</ul>
            </div>
          </div>
      </div>
      {% endfor %}
    </div>
    <div class="col" id=second_column>
      <h3>Trip Details</h3>
      <div class="container">
        {% for event in trip_events  %}
        <ul class="list-group"><a href="{% url 'golf_trip:eventDetail' pk=event.pk %}">{{event.tee_time}} - {{event.course.course}}</a></ul>
        {% comment %} <ul class="list-group">{{event.event_time}} - {{event.course.course}}</ul> {% endcomment %}
        {% endfor %}
      </div>

    </div>
    <div class="col" id=third_column>
      <h3>Course Information<h3>
      <ul class="list-group"><a href="https://arcadiabluffs.com/">Arcadia Bluffs</a></ul>
      <ul class="list-group"><a href='https://www.treetops.com/golf/'>Treetops</a></ul>
    </div>
  </div>
</div>

{% endblock bodyblock %}



{% endblock %}

golf_coordinator/golf_trip/templates/golf_trip/trip_event_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="display-4 pb-2" style='text-align: center'>Trip Schedule</h1>
<div class="row gx-5">
{% for date in trip_dates %}
        <div class="col-lg-4 mb-5">
            <div class="card h-100 shadow border-0 my-card" >
                <div class="card-body p-4">
                    <a class="text-decoration-none link-dark stretched-link" href="{% url 'golf_trip:event_teetime' event_day=date.event_time %}"><h5 class="card-title mb-3">{{date.event_time}}</h5></a>

                    {% for event in trip_events  %}
                        {% if date.event_time|date:"M D Y" == event.event_time|date:"M D Y" %}
                            <p class="card-text mb-0">{{event.course.course}}</p>
                        {% endif %}
                    {% endfor %}
                </div>
                 
            </div>
        </div>        
{% endfor %}

{% for course in courses %}
        {{course.course_name}}
{% endfor %}
{% endblock  %}

golf_coordinator/golf_trip/templates/golf_trip/trip_michigan_index.html
{% extends 'base.html' %}
{% load static %}
            <!-- Header-->
            {% block content %}
            <header class="bg-dark py-5">
                <div class="container px-5">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-8 col-xl-7 col-xxl-6">
                            <div class="my-5 text-center text-xl-start">
                                <h1 class="display-5 fw-bolder text-white mb-2">Golf Trip 2023</h1>
                                <p class="lead fw-normal text-white-50 mb-4">Arcadia Bluffs and Treetops August 17-20 2023</p>
                                <a class="btn btn-primary btn-lg " href="{% url 'golf_trip:trip_standings' %}">View Standing</a>

                            </div>
                        </div>
                        <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'GTP_logo.jpg' %}"  width=500/></div>
                    </div>
                </div>
            </header>
            <!-- Features section-->
            <section class="py-5" id="features">
                <div class="container px-5 my-5">
                    <div class="row gx-5">
                        <div class="col-lg-4 mb-5 mb-lg-0 text-center">
                            <h2 class="fw-bolder mb-0 ">Trip Information</h2>
                        </div>
                        <div class="col-lg-8">
                            <div class="row gx-5 row-cols-1 row-cols-md-2 text-center">
                                <div class="col mb-5 mb-md-0 h-100">
                                    <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'golf_trip:events_list' %}"><i class="fa-regular fa-calendar-days"></i></a>
                                    <h2 class="h5">Schedule</h2>
                                    <p class="mb-0">Day's Events and Tee time</p>
                                </div>
                                <div class="col mb-5 h-100">
                                    <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'golf_trip:players_list' %}"><i class="fa-solid fa-users"></i></a>
                                    <h2 class="h5">Players</h2>
                                    <p class="mb-0">List of players and their handicaps</p>
                                </div>
                                <div class="col h-100">
                                    <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'bookie:bet_overview' %}"><i class="fa-solid fa-coins"></i></a>
                                    <h2 class="h5">Bookie</h2>
                                    <p class="mb-0">Track the trip's bets</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0 text-white">Golf Trip 2023 </div></div>
                    <div class="col-auto">
                        <a class="link-light small">Developed by: Everett Kennedy</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>

{% endblock  %}

golf_coordinator/golf_trip/templates/golf_trip/trip_streamsong_index.html
{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% bootstrap_messages %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css" />
    </head>
    <body style="background-color: lightblue;">
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'golf_trip:home' %}">
                    <i class="fa-solid fa-golf-ball-tee"></i>  Golf Trip Manager
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <span><ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Courses</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <li><a class="dropdown-item" href={% url 'courses:golf_course_list' %}>Course List</a></li>
                          <li><a class="dropdown-item" href={% url 'courses:course_new' %}>Add Course</a></li>
                        </ul>
                      </li>
                        <a class="nav-link" href="{% url 'golf_trip:event_history' %}">Previous Trips</a>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        
                        <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>
                    </ul></span>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5" id='page_row'>
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'GTP_logo.jpg' %}"/></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">Streamsong 2022</h1>
                    <br>
                    
                   
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">CALL AND MAKE YOUR DEPOSIT NOW: (866) 348-5249</p></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="card-header"><h2 class="card-title" style="text-align: center;">Players</h2></div>
                            {% for golfer in golfers %}
                                <div class="container">
                                    <div class="row">
                                        <div class="col-20">
                                        <ul class="list-group" style="text-align: center;">{{golfer.golfer.first_name}} {{golfer.golfer.last_name}}: {{golfer.hcp_index}}</ul>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="card-header"><h2 class="card-title" style="text-align: center;">Trip Details</h2></div>
                            {% for event in trip_events  %}
                                <ul class="list-group" style="text-align: center;"><a href="{% url 'golf_trip:eventDetail' pk=event.pk %}">{{event.tee_time}} - {{event.course.course}}</a></ul>
                            {% endfor %}
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Three</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

golf_coordinator/golf_trip/templates/golf_trip/trip_teetime_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class='container'>
    
    <h1 style='text-align: center; padding-bottom: 15px;'>Tee Time Schedule</h1>
<div class="row  justify-content-center">
        {% for teetime in trip_teetime_list %}
            <div class="card shadow-sm" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{teetime.tee_time_time}}<span style="float: right" class="fa-solid fa-circle-exclamation" data-toggle="popover" data-bs-html="true" title="Tee Time Details" 
                                                                            data-bs-content="Course: {{ teetime.tee.course.course_name}}<br/>
                                                                                            Tee: <a href='{% url 'courses:golf_tee_detail' pk=teetime.tee.pk %}' class='card-link'>{{teetime.tee.tee_name}}</a><br/>
                                                                                            Format: {{teetime.gametype}}"></span>
                    </h5> 
                    {% if not teetime.Players.all %}
                        <p class="card-text">No players assigned </p> 
                    {% else %}
                        {% for players in teetime.Players.all  %}
                            <p class="card-text player-text">Player #{{forloop.counter}}: {{ players.golfer.first_name}} {{ players.golfer.last_name}}</p>
                        {% endfor %}
                    {% endif %}

                    {% if teetime.teeTime_Complete is True %}
                        <a></a>
                    {% else %}
                        <a class="btn btn-success btn-sm mt-1" href="{% url 'round:round_submit' teetime_pk=teetime.pk %}" class="card-link">Enter Score  <i class="fa-solid fa-pencil"></i></a>  
                        <a  class="btn btn-primary btn-sm mt-1" href="{% url 'bookie:bet_teetime' teetime_pk=teetime.pk %}" class="card-link"> Place Bets    <i class="fa-solid fa-coins fa-xl"></i></a>
                    {% endif %}

                    {% if teetime.teeTime_Complete is True %}
                    <a class="btn btn-success btn-sm" href="{% url 'round:completed_round' pk=teetime.pk %}" class="card-link" style="padding-right:15px">View Card <i class="fa-solid fa-binoculars"></i></a>
                    <button style="float: right; padding-left:15px"class="btn btn-danger btn-sm">Closed <i class="fa-solid fa-coins fa-xl"></i>
                    {% else %}
                        <a></a>
                    {% endif %}       
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="d-grid gap-2 col-4 pt-1 mx-auto text-center">
        <a class="btn-lg btn-primary " href="{% url 'golf_trip:events_list' %}" role="button">Back</a>
    </div>

{% endblock %}